kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim2
  labels:
    app: postgres
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
