kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume2
  labels:
    type: local
    app: postgres
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
