apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reckon-api
  template:
    metadata:
      labels:
        app: reckon-api
    spec:
      containers:
        - name: reckon-api
          image: reckon-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: reckon-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001